// Generated by tools/generate_dashboard_config.py. Do not hand-edit.
window.RECEIPTPULSE_CONFIG = {
  "apiBaseUrl": "",
  "demo": {
    "enabled": true,
    "autoFallback": true,
    "sampleDataPath": "./data/demo-dashboard.json",
    "user": {
      "id": "demo-cloud-operator",
      "name": "Cloud Demo Operator",
      "email": "demo@receiptpulse.dev"
    }
  },
  "auth": {
    "hostedUiDomain": "",
    "clientId": "",
    "region": "ap-south-1",
    "appPath": "./app.html",
    "redirectSignIn": "https://receiptpulse-cloud-demo.onrender.com/",
    "redirectSignOut": "https://receiptpulse-cloud-demo.onrender.com/",
    "scopes": [
      "openid",
      "profile"
    ]
  }
};
